// This file is part of the happyDeliver (R) project.
// Copyright (c) 2025-2026 happyDomain
// Authors: Pierre-Olivier Mercier, et al.
//
// This program is offered under a commercial and under the AGPL license.
// For commercial licensing, contact us at <contact@happydomain.org>.
//
// For AGPL licensing:
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package bimi

import (
	"crypto/x509"
	"encoding/pem"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// TestEmbeddedVMCRoots checks the bundle that travels with the binary: it is
// generated by roots/update.sh from the network, so what it actually contains
// is worth asserting rather than assuming.
func TestEmbeddedVMCRoots(t *testing.T) {
	pool, err := EmbeddedVMCRoots()
	if err != nil {
		t.Fatalf("EmbeddedVMCRoots() error = %v", err)
	}
	if pool == nil {
		t.Fatal("EmbeddedVMCRoots() returned a nil pool")
	}

	subjects := parseTestPEMChain(t, embeddedVMCRoots)
	if len(subjects) == 0 {
		t.Fatal("the embedded bundle holds no certificate")
	}

	now := time.Now()
	for _, cert := range subjects {
		name := cert.Subject.CommonName

		// Only roots belong in the bundle: an intermediate accepted as an
		// anchor would let a chain stop short of the authority it is meant
		// to lead back to.
		if !cert.IsCA {
			t.Errorf("%s is not a CA certificate", name)
		}
		if err := cert.CheckSignatureFrom(cert); err != nil {
			t.Errorf("%s is not self-signed: %v", name, err)
		}
		if now.After(cert.NotAfter) {
			t.Errorf("%s expired on %s: refresh the bundle with roots/update.sh", name, cert.NotAfter)
		}
	}
}

// parseTestPEMChain decodes every certificate of a PEM bundle.
func parseTestPEMChain(t *testing.T, content []byte) []*x509.Certificate {
	t.Helper()

	var certs []*x509.Certificate
	for block, rest := pem.Decode(content); block != nil; block, rest = pem.Decode(rest) {
		if block.Type != "CERTIFICATE" {
			continue
		}
		cert, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			t.Fatalf("unable to parse a certificate of the bundle: %v", err)
		}
		certs = append(certs, cert)
	}

	return certs
}

func TestLoadVMCRoots(t *testing.T) {
	dir := t.TempDir()

	valid := filepath.Join(dir, "roots.pem")
	if err := os.WriteFile(valid, embeddedVMCRoots, 0o600); err != nil {
		t.Fatal(err)
	}

	empty := filepath.Join(dir, "empty.pem")
	if err := os.WriteFile(empty, nil, 0o600); err != nil {
		t.Fatal(err)
	}

	// A file that parses as text but carries no certificate: the shape a
	// truncated download or a mistaken path takes.
	notPEM := filepath.Join(dir, "notes.txt")
	if err := os.WriteFile(notPEM, []byte("# roots go here\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name     string
		path     string
		wantPool bool
		wantErr  bool
	}{
		{"embedded bundle by default", "", true, false},
		{"disabled leaves no pool", DisableVMCRoots, false, false},
		{"file of roots", valid, true, false},
		{"missing file", filepath.Join(dir, "absent.pem"), false, true},
		{"empty file", empty, false, true},
		{"file without certificate", notPEM, false, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			pool, err := LoadVMCRoots(tt.path)
			if (err != nil) != tt.wantErr {
				t.Fatalf("LoadVMCRoots(%q) error = %v, wantErr %v", tt.path, err, tt.wantErr)
			}
			if (pool != nil) != tt.wantPool {
				t.Errorf("LoadVMCRoots(%q) pool = %v, want pool %v", tt.path, pool, tt.wantPool)
			}
		})
	}
}
