#!/bin/sh
# Regenerates vmc-roots.pem from the Mark Verifying Authority roots published
# at https://bimigroup.org/vmc-issuers/.
#
# The BIMI Group lists the MVAs but publishes no aggregated bundle: each root
# is fetched from its own authority here. Run this when an MVA is added to the
# list or rolls its root, then check the printed fingerprints against the CA's
# own repository before committing -- this script trusts the network, and the
# whole point of the bundle is that it should not.
#
# Only roots belong here. Intermediates are taken from the chain published at
# the a= URL (see AnalyzeVMC): trusting one as an anchor would let a chain skip
# the root it is supposed to lead back to.

set -eu

cd "$(dirname "$0")"

out=vmc-roots.pem
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

date=$(date -u +%Y-%m-%d)

{
	echo "# Root certificates of the Mark Verifying Authorities recognised by the"
	echo "# BIMI Group, as listed on https://bimigroup.org/vmc-issuers/."
	echo "#"
	echo "# Generated by update.sh on $date. Do not edit by hand."
} > "$out"

fetch() {
	mva=$1
	url=$2

	curl -sSfL -o "$tmp/raw" "$url"

	# GlobalSign publishes DER; the others PEM. Normalise both, which also
	# drops any human-readable text a publisher wraps around the block.
	if ! openssl x509 -in "$tmp/raw" -out "$tmp/cert.pem" 2>/dev/null; then
		openssl x509 -inform DER -in "$tmp/raw" -out "$tmp/cert.pem"
	fi

	subject=$(openssl x509 -in "$tmp/cert.pem" -noout -subject | sed 's/^subject=[ ]*//')
	fingerprint=$(openssl x509 -in "$tmp/cert.pem" -noout -fingerprint -sha256 | sed 's/^.*=//')

	{
		echo
		echo "# $mva"
		echo "# Subject: $subject"
		echo "# SHA-256: $fingerprint"
		echo "# Source: $url"
		echo "# Retrieved: $date"
		cat "$tmp/cert.pem"
	} >> "$out"

	echo "$mva: $fingerprint"
}

fetch "DigiCert" "https://bimigroup.org/certs/digicert.pem"
fetch "GlobalSign" "http://secure.globalsign.com/cacert/gsverifiedmarkrootr42.crt"
fetch "SSL.com (ECC)" "https://ssl.com/repo/certs/SSL.com-VMC-Root-2024-ECC.pem"
fetch "SSL.com (RSA)" "https://ssl.com/repo/certs/SSL.com-VMC-Root-2024-RSA.pem"
