// Code generated from schema/SVG_PS-latest.rng by gen/main.go. DO NOT EDIT.

package svgps

var profile = map[string]element{
	"circle": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"cx":                {},
			"cy":                {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"r":                 {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"defs": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
		children: map[string]bool{"circle": true, "defs": true, "ellipse": true, "g": true, "line": true, "linearGradient": true, "path": true, "polygon": true, "polyline": true, "radialGradient": true, "rect": true, "solidColor": true, "text": true, "textArea": true, "use": true},
	},
	"desc": {
		attrs: map[string]attr{
			"about":                 {},
			"buffered-rendering":    {enum: []string{"auto", "dynamic", "static", "inherit"}},
			"class":                 {},
			"content":               {},
			"datatype":              {},
			"display":               {enum: []string{"inline", "block", "list-item", "run-in", "compact", "marker", "table", "inline-table", "table-row-group", "table-header-group", "table-footer-group", "table-row", "table-column-group", "table-column", "table-cell", "table-caption", "none", "inherit"}},
			"id":                    {},
			"image-rendering":       {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"property":              {},
			"rel":                   {},
			"requiredFonts":         {},
			"resource":              {},
			"rev":                   {},
			"role":                  {},
			"shape-rendering":       {enum: []string{"auto", "optimizeSpeed", "crispEdges", "geometricPrecision", "inherit"}},
			"systemLanguage":        {},
			"text-rendering":        {enum: []string{"auto", "optimizeSpeed", "optimizeLegibility", "geometricPrecision", "inherit"}},
			"typeof":                {},
			"viewport-fill":         {},
			"viewport-fill-opacity": {},
			"visibility":            {enum: []string{"visible", "hidden", "collapse", "inherit"}},
			"xml:base":              {},
			"xml:id":                {},
			"xml:lang":              {},
			"xml:space":             {enum: []string{"default", "preserve"}},
		},
		allowsText: true,
	},
	"ellipse": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"cx":                {},
			"cy":                {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"rx":                {},
			"ry":                {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"font": {
		attrs: map[string]attr{
			"horiz-adv-x":  {},
			"horiz-origin": {},
		},
		children: map[string]bool{"desc": true, "font-face": true, "glyph": true, "hkern": true},
	},
	"font-face": {
		attrs: map[string]attr{
			"accented-height":         {},
			"alphabetic":              {},
			"ascent":                  {},
			"bbox":                    {},
			"cap-height":              {},
			"descent":                 {},
			"font-family":             {},
			"font-stretch":            {},
			"font-style":              {},
			"font-variant":            {},
			"font-weight":             {},
			"hanging":                 {},
			"ideographic":             {},
			"mathematical":            {},
			"overline-position":       {},
			"overline-thickness":      {},
			"panose-1":                {},
			"slope":                   {},
			"stemh":                   {},
			"stemv":                   {},
			"strikethrough-position":  {},
			"strikethrough-thickness": {},
			"underline-position":      {},
			"underline-thickness":     {},
			"unicode-range":           {},
			"units-per-em":            {},
			"widths":                  {},
			"x-height":                {},
		},
		children: map[string]bool{"desc": true},
	},
	"g": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
		children: map[string]bool{"circle": true, "defs": true, "ellipse": true, "g": true, "line": true, "linearGradient": true, "path": true, "polygon": true, "polyline": true, "radialGradient": true, "rect": true, "solidColor": true, "text": true, "textArea": true, "use": true},
	},
	"glyph": {
		attrs: map[string]attr{
			"arabic-form": {},
			"glyph-name":  {},
			"lang":        {},
			"unicode":     {},
		},
		children: map[string]bool{"desc": true},
	},
	"hkern": {
		attrs: map[string]attr{
			"g1": {},
			"g2": {},
			"k":  {},
			"u1": {},
			"u2": {},
		},
		children: map[string]bool{"desc": true},
	},
	"line": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"x1":                {},
			"x2":                {},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
			"y1":                {},
			"y2":                {},
		},
	},
	"linearGradient": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"gradientUnits":     {enum: []string{"userSpaceOnUse", "objectBoundingBox"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"x1":                {},
			"x2":                {},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
			"y1":                {},
			"y2":                {},
		},
		children: map[string]bool{"stop": true},
	},
	"metadata": {
		allowsText: true,
	},
	"path": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"d":                 {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"pathLength":        {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"polygon": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"points":            {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"polyline": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"points":            {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"radialGradient": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"cx":                {},
			"cy":                {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"gradientUnits":     {enum: []string{"userSpaceOnUse", "objectBoundingBox"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"r":                 {},
			"rel":               {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
		children: map[string]bool{"stop": true},
	},
	"rect": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"height":            {},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"rx":                {},
			"ry":                {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"width":             {},
			"x":                 {},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
			"y":                 {},
		},
	},
	"solidColor": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"stop": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"offset":            {},
			"property":          {},
			"rel":               {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
		},
	},
	"svg": {
		attrs: map[string]attr{
			"about":                     {},
			"baseProfile":               {required: true, enum: []string{"tiny-ps"}},
			"class":                     {},
			"color":                     {},
			"color-rendering":           {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":                   {},
			"contentScriptType":         {},
			"datatype":                  {},
			"direction":                 {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":             {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"externalResourcesRequired": {enum: []string{"false"}},
			"fill":                      {},
			"fill-opacity":              {},
			"fill-rule":                 {enum: []string{"inherit", "nonzero", "evenodd"}},
			"focusable":                 {enum: []string{"false"}},
			"font-family":               {},
			"font-size":                 {},
			"font-style":                {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":              {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":               {enum: []string{"normal", "bold", "bolder", "lighter"}},
			"height":                    {},
			"id":                        {},
			"line-increment":            {},
			"playbackOrder":             {enum: []string{"all"}},
			"preserveAspectRatio":       {pattern: "\\s*(none|xMidYMid)\\s*(meet)?\\s*"},
			"property":                  {},
			"rel":                       {},
			"resource":                  {},
			"rev":                       {},
			"role":                      {},
			"snapshotTime":              {enum: []string{"none"}},
			"solid-color":               {},
			"solid-opacity":             {},
			"stop-color":                {},
			"stop-opacity":              {},
			"stroke":                    {},
			"stroke-dasharray":          {},
			"stroke-dashoffset":         {},
			"stroke-linecap":            {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":           {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit":         {},
			"stroke-opacity":            {},
			"stroke-width":              {},
			"text-align":                {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":               {enum: []string{"start", "middle", "end", "inherit"}},
			"timelineBegin":             {enum: []string{"onLoad"}},
			"typeof":                    {},
			"unicode-bidi":              {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":             {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"version":                   {required: true, enum: []string{"1.2"}},
			"viewBox":                   {},
			"width":                     {},
			"xml:base":                  {},
			"xml:id":                    {},
			"xml:lang":                  {},
			"xml:space":                 {enum: []string{"default", "preserve"}},
			"zoomAndPan":                {enum: []string{"disable"}},
		},
		firstChild: "title",
		children:   map[string]bool{"circle": true, "defs": true, "desc": true, "ellipse": true, "g": true, "line": true, "linearGradient": true, "metadata": true, "path": true, "polygon": true, "polyline": true, "radialGradient": true, "rect": true, "solidColor": true, "text": true, "textArea": true, "use": true},
	},
	"text": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"editable":          {enum: []string{"none"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"rotate":            {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"x":                 {},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
			"y":                 {},
		},
		allowsText: true,
	},
	"textArea": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"height":            {},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"width":             {},
			"x":                 {},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
			"y":                 {},
		},
		allowsText: true,
	},
	"title": {
		attrs: map[string]attr{
			"about":                 {},
			"buffered-rendering":    {enum: []string{"auto", "dynamic", "static", "inherit"}},
			"class":                 {},
			"content":               {},
			"datatype":              {},
			"display":               {enum: []string{"inline", "block", "list-item", "run-in", "compact", "marker", "table", "inline-table", "table-row-group", "table-header-group", "table-footer-group", "table-row", "table-column-group", "table-column", "table-cell", "table-caption", "none", "inherit"}},
			"id":                    {},
			"image-rendering":       {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"property":              {},
			"rel":                   {},
			"requiredFonts":         {},
			"resource":              {},
			"rev":                   {},
			"role":                  {},
			"shape-rendering":       {enum: []string{"auto", "optimizeSpeed", "crispEdges", "geometricPrecision", "inherit"}},
			"systemLanguage":        {},
			"text-rendering":        {enum: []string{"auto", "optimizeSpeed", "optimizeLegibility", "geometricPrecision", "inherit"}},
			"typeof":                {},
			"viewport-fill":         {},
			"viewport-fill-opacity": {},
			"visibility":            {enum: []string{"visible", "hidden", "collapse", "inherit"}},
			"xml:base":              {},
			"xml:id":                {},
			"xml:lang":              {},
			"xml:space":             {enum: []string{"default", "preserve"}},
		},
		allowsText: true,
	},
	"use": {
		attrs: map[string]attr{
			"about":             {},
			"class":             {},
			"color":             {},
			"color-rendering":   {enum: []string{"auto", "optimizeSpeed", "optimizeQuality", "inherit"}},
			"content":           {},
			"datatype":          {},
			"direction":         {enum: []string{"ltr", "rtl", "inherit"}},
			"display-align":     {enum: []string{"auto", "before", "center", "after", "inherit"}},
			"fill":              {},
			"fill-opacity":      {},
			"fill-rule":         {enum: []string{"inherit", "nonzero", "evenodd"}},
			"font-family":       {},
			"font-size":         {},
			"font-style":        {enum: []string{"normal", "italic", "oblique", "inherit"}},
			"font-variant":      {enum: []string{"normal", "small-caps", "inherit"}},
			"font-weight":       {enum: []string{"normal", "bold", "bolder", "lighter", "inherit"}},
			"href":              {},
			"id":                {},
			"line-increment":    {},
			"property":          {},
			"rel":               {},
			"requiredFonts":     {},
			"resource":          {},
			"rev":               {},
			"role":              {},
			"solid-color":       {},
			"solid-opacity":     {},
			"stop-color":        {},
			"stop-opacity":      {},
			"stroke":            {},
			"stroke-dasharray":  {},
			"stroke-dashoffset": {},
			"stroke-linecap":    {enum: []string{"butt", "round", "square", "inherit"}},
			"stroke-linejoin":   {enum: []string{"miter", "round", "bevel", "inherit"}},
			"stroke-miterlimit": {},
			"stroke-opacity":    {},
			"stroke-width":      {},
			"systemLanguage":    {},
			"text-align":        {enum: []string{"start", "center", "end", "inherit"}},
			"text-anchor":       {enum: []string{"start", "middle", "end", "inherit"}},
			"transform":         {},
			"typeof":            {},
			"unicode-bidi":      {enum: []string{"normal", "embed", "bidi-override", "inherit"}},
			"vector-effect":     {enum: []string{"none", "non-scaling-stroke", "inherit"}},
			"x":                 {},
			"xml:base":          {},
			"xml:id":            {},
			"xml:lang":          {},
			"xml:space":         {enum: []string{"default", "preserve"}},
			"y":                 {},
		},
	},
}
