package: model
generate:
  models: true
  embedded-spec: true
output: internal/model/types.gen.go
output-options:
  skip-prune: true
compatibility:
  always-prefix-enum-values: true
import-mapping:
  ./schemas.yaml: "-"
